[workspace]
members = ["htmxology", "htmxology-macros"]
#default-members = ["htmxology"]
resolver = "2"

[workspace.dependencies]
htmxology = { path = "./htmxology" }
htmxology-macros = { path = "./htmxology-macros", version = "0.1.0" }

anyhow = "1"
askama = { version = "0.12", features = ["with-axum"] }
askama_axum = { version = "0.4" }
axum = "0.7"
convert_case = "0.6"
itertools = "0.13"
listenfd = "1"
http = "1"
netdev = "0.31"
proc-macro2 = "1"
quote = "1"
percent-encoding = "2"
regex = "1"
serde = { version ="1", features = ["derive"] }
serde_urlencoded = "0.7"
syn = { version = "2", features = ["full"] }
thiserror = "2"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3" }
uuid = { version = "1", features = ["v4"] }
